# https://taskfile.dev

version: '3'

vars:
  VERSION:
    sh: dover -f 000a0
  ZIP_FILE: reveal-{{.VERSION}}-win.zip

tasks:
  build:
    cmds:
      - wails build --clean
    silent: true

  build:windows:
    cmds:
      - wails build --clean --platform="windows/amd64"
    silent: true

  build:darwin:
    cmds:
      - wails build --clean --platform="darwin/arm64"
    silent: true

  release:windows:
    dir: build/bin
    cmds:
      - zip {{.ZIP_FILE}} reveal.exe
      - zip -u {{.ZIP_FILE}} ../../README.md
      - mv {{.ZIP_FILE}} ../../releases

  release:
    cmds:
      - goreleaser release --rm-dist --skip-announce

