// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClipboard():Promise<string>;

export function PutClipboard(arg1:string):Promise<void>;
