// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetSegmentSize() {
  return window['go']['main']['App']['GetSegmentSize']();
}

export function GetTimeout() {
  return window['go']['main']['App']['GetTimeout']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function PutClipboard(arg1) {
  return window['go']['main']['App']['PutClipboard'](arg1);
}
